import {
  UserProfile,
  AcademicMetric,
  Subject,
  StudyPriorityItem,
  UpcomingEvent,
  StudyPlanDay,
  AiChatMessage,
  TargetCalculationPreview,
} from "@/types";

export const MOCK_USER: UserProfile = {
  id: "usr_mock_001",
  name: "Alex Rivera",
  email: "alex.rivera@eng.univ.edu",
  university: "National Institute of Technology",
  branch: "Computer Science & Engineering",
  semester: 5,
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  targetCgpa: 8.8,
};

export const MOCK_METRICS: AcademicMetric = {
  cgpa: 8.34,
  targetCgpa: 8.8,
  currentSgpa: 8.52,
  attendancePercentage: 86.5,
  totalCredits: 120,
  completedCredits: 96,
  activeBacklogs: 0,
};

export const MOCK_SUBJECTS: Subject[] = [
  {
    id: "sub_01",
    code: "CS501",
    name: "Analysis of Algorithms",
    credits: 4,
    faculty: "Dr. K. Raman",
    currentScore: 68,
    targetGrade: "A+",
    attendance: 79.0,
    trend: "down",
    trendValue: "-4% vs last test",
    status: "Needs Attention",
    assessments: [
      { id: "a1", title: "Internal Assessment 1", type: "internal", maxMarks: 20, obtainedMarks: 13, weightagePercentage: 15 },
      { id: "a2", title: "Midterm Exam", type: "midterm", maxMarks: 50, obtainedMarks: 34, weightagePercentage: 25 },
      { id: "a3", title: "Algorithm Assignment 1", type: "assignment", maxMarks: 10, obtainedMarks: 8, weightagePercentage: 10 },
      { id: "a4", title: "End Semester Exam", type: "endterm", maxMarks: 100, weightagePercentage: 50 },
    ],
  },
  {
    id: "sub_02",
    code: "CS502",
    name: "Computer Organization & Architecture",
    credits: 4,
    faculty: "Prof. S. Mehra",
    currentScore: 74,
    targetGrade: "A",
    attendance: 88.0,
    trend: "up",
    trendValue: "+6% vs last test",
    status: "Good Standing",
    assessments: [
      { id: "a5", title: "Internal Assessment 1", type: "internal", maxMarks: 20, obtainedMarks: 15, weightagePercentage: 15 },
      { id: "a6", title: "Midterm Exam", type: "midterm", maxMarks: 50, obtainedMarks: 38, weightagePercentage: 25 },
      { id: "a7", title: "Pipelining Assignment", type: "assignment", maxMarks: 10, obtainedMarks: 9, weightagePercentage: 10 },
      { id: "a8", title: "End Semester Exam", type: "endterm", maxMarks: 100, weightagePercentage: 50 },
    ],
  },
  {
    id: "sub_03",
    code: "CS503",
    name: "Database Management Systems",
    credits: 3,
    faculty: "Dr. Anita Rao",
    currentScore: 88,
    targetGrade: "O",
    attendance: 94.0,
    trend: "up",
    trendValue: "+2% vs last test",
    status: "Good Standing",
    assessments: [
      { id: "a9", title: "Internal Assessment 1", type: "internal", maxMarks: 20, obtainedMarks: 18, weightagePercentage: 15 },
      { id: "a10", title: "Midterm Exam", type: "midterm", maxMarks: 50, obtainedMarks: 45, weightagePercentage: 25 },
      { id: "a11", title: "SQL Project", type: "assignment", maxMarks: 10, obtainedMarks: 10, weightagePercentage: 10 },
      { id: "a12", title: "End Semester Exam", type: "endterm", maxMarks: 100, weightagePercentage: 50 },
    ],
  },
  {
    id: "sub_04",
    code: "CS504",
    name: "Discrete Mathematical Structures",
    credits: 3,
    faculty: "Prof. V. Sharma",
    currentScore: 61,
    targetGrade: "B+",
    attendance: 76.5,
    trend: "down",
    trendValue: "-7% vs quiz average",
    status: "Critical Focus",
    assessments: [
      { id: "a13", title: "Quiz 1 & 2", type: "internal", maxMarks: 20, obtainedMarks: 11, weightagePercentage: 15 },
      { id: "a14", title: "Midterm Exam", type: "midterm", maxMarks: 50, obtainedMarks: 29, weightagePercentage: 25 },
      { id: "a15", title: "Graph Theory Problem Set", type: "assignment", maxMarks: 10, obtainedMarks: 7, weightagePercentage: 10 },
      { id: "a16", title: "End Semester Exam", type: "endterm", maxMarks: 100, weightagePercentage: 50 },
    ],
  },
  {
    id: "sub_05",
    code: "CS505",
    name: "Operating Systems Lab",
    credits: 2,
    faculty: "Er. P. Deshmukh",
    currentScore: 92,
    targetGrade: "O",
    attendance: 95.0,
    trend: "stable",
    trendValue: "0% deviation",
    status: "Good Standing",
    assessments: [
      { id: "a17", title: "Lab Practical 1", type: "lab", maxMarks: 30, obtainedMarks: 28, weightagePercentage: 30 },
      { id: "a18", title: "Shell Scripting Viva", type: "lab", maxMarks: 20, obtainedMarks: 19, weightagePercentage: 20 },
      { id: "a19", title: "Final Lab Exam", type: "endterm", maxMarks: 50, weightagePercentage: 50 },
    ],
  },
];

export const MOCK_PRIORITY_ITEMS: StudyPriorityItem[] = [
  {
    id: "pri_1",
    rank: 1,
    subjectCode: "CS501",
    subjectName: "Analysis of Algorithms",
    priorityScore: 92,
    urgency: "High",
    impactFactor: "High (4 Credits)",
    reason: "Current average (68%) puts your target 'A+' at risk; Midterm weightage requires >= 82% on final exam.",
    recommendedAction: "Review Dynamic Programming & Graph Theory recurrences; allocate 90m tonight.",
    creditWeight: 4,
  },
  {
    id: "pri_2",
    rank: 2,
    subjectCode: "CS504",
    subjectName: "Discrete Mathematical Structures",
    priorityScore: 84,
    urgency: "High",
    impactFactor: "Medium (3 Credits)",
    reason: "Score dropped 7% after Graph Theory quiz; Attendance is close to minimum 75% cutoff (76.5%).",
    recommendedAction: "Complete past year theorem proofs on Relations and Combinatorics.",
    creditWeight: 3,
  },
  {
    id: "pri_3",
    rank: 3,
    subjectCode: "CS502",
    subjectName: "Computer Organization & Architecture",
    priorityScore: 66,
    urgency: "Medium",
    impactFactor: "High (4 Credits)",
    reason: "On track for Grade A (74%), but Cache Memory & Pipeline hazard questions need reinforcement.",
    recommendedAction: "Practice 5 numerical problems on direct and associative cache mapping.",
    creditWeight: 4,
  },
];

export const MOCK_UPCOMING_EVENTS: UpcomingEvent[] = [
  {
    id: "evt_1",
    title: "Midterm Assessment 2",
    subject: "Analysis of Algorithms (CS501)",
    date: "Tomorrow, 10:00 AM",
    daysLeft: 1,
    type: "Exam",
    priority: "High",
  },
  {
    id: "evt_2",
    title: "SQL Query Optimization Assignment",
    subject: "Database Management Systems (CS503)",
    date: "In 3 days (Friday)",
    daysLeft: 3,
    type: "Assignment",
    priority: "Medium",
  },
  {
    id: "evt_3",
    title: "Memory Organization Quiz",
    subject: "Computer Organization (CS502)",
    date: "Next Monday",
    daysLeft: 6,
    type: "Quiz",
    priority: "Medium",
  },
  {
    id: "evt_4",
    title: "IPC & Semaphores Lab Viva",
    subject: "Operating Systems Lab (CS505)",
    date: "Next Wednesday",
    daysLeft: 8,
    type: "Lab Evaluation",
    priority: "Low",
  },
];

export const MOCK_STUDY_PLAN: StudyPlanDay[] = [
  {
    day: "Monday",
    date: "Today",
    isToday: true,
    totalHours: 3.5,
    tasks: [
      {
        id: "tsk_1",
        subject: "Analysis of Algorithms",
        title: "Dynamic Programming: Matrix Chain Multiplication & LCS",
        durationMinutes: 90,
        completed: false,
        priority: "High",
        timeSlot: "06:30 PM - 08:00 PM",
      },
      {
        id: "tsk_2",
        subject: "Discrete Structures",
        title: "Relations: Equivalence classes & Hasse diagrams",
        durationMinutes: 60,
        completed: true,
        priority: "High",
        timeSlot: "08:30 PM - 09:30 PM",
      },
      {
        id: "tsk_3",
        subject: "DBMS",
        title: "B+ Tree indexing revision",
        durationMinutes: 60,
        completed: false,
        priority: "Low",
        timeSlot: "10:00 PM - 11:00 PM",
      },
    ],
  },
  {
    day: "Tuesday",
    date: "Tomorrow",
    isToday: false,
    totalHours: 4.0,
    tasks: [
      {
        id: "tsk_4",
        subject: "Analysis of Algorithms",
        title: "Greedy choice property & Huffman coding practice",
        durationMinutes: 90,
        completed: false,
        priority: "High",
        timeSlot: "06:00 PM - 07:30 PM",
      },
      {
        id: "tsk_5",
        subject: "Computer Organization",
        title: "Pipelining hazards & branch prediction numericals",
        durationMinutes: 90,
        completed: false,
        priority: "Medium",
        timeSlot: "08:00 PM - 09:30 PM",
      },
      {
        id: "tsk_6",
        subject: "OS Lab",
        title: "Producer-Consumer problem implementation in C",
        durationMinutes: 60,
        completed: false,
        priority: "Low",
        timeSlot: "10:00 PM - 11:00 PM",
      },
    ],
  },
  {
    day: "Wednesday",
    date: "Day After",
    isToday: false,
    totalHours: 3.0,
    tasks: [
      {
        id: "tsk_7",
        subject: "DBMS",
        title: "Normalization: 3NF & BCNF decomposition examples",
        durationMinutes: 75,
        completed: false,
        priority: "Medium",
        timeSlot: "07:00 PM - 08:15 PM",
      },
      {
        id: "tsk_8",
        subject: "Discrete Structures",
        title: "Euler and Hamiltonian graph proofs",
        durationMinutes: 75,
        completed: false,
        priority: "High",
        timeSlot: "08:30 PM - 09:45 PM",
      },
    ],
  },
];

export const MOCK_AI_CONVERSATION: AiChatMessage[] = [
  {
    id: "msg_1",
    sender: "assistant",
    content:
      "Hello Alex! I am your **AcaVise Academic Assistant**. Based on your current Semester 5 progress, your CGPA is **8.34** and your target is **8.80**. What would you like to examine today?",
    timestamp: "10:00 AM",
    suggestions: [
      "What should I study today?",
      "What do I need in Algorithms to score an A+?",
      "How does a 9.2 SGPA this semester impact my CGPA?",
    ],
  },
  {
    id: "msg_2",
    sender: "user",
    content: "What should I focus on first this evening?",
    timestamp: "10:02 AM",
  },
  {
    id: "msg_3",
    sender: "assistant",
    content:
      "Based on your **Study Priority Engine**, your top priority tonight is **CS501: Analysis of Algorithms (4 Credits)**. You have Midterm Assessment 2 tomorrow, and your current performance is at 68% against an A+ target. I recommend 90 minutes on Dynamic Programming recurrences before 8:00 PM.",
    timestamp: "10:02 AM",
    suggestions: [
      "Show me sample algorithm exam questions",
      "Calculate minimum marks for A+ grade",
      "Adjust today's study schedule",
    ],
  },
];

export const MOCK_TARGET_PREVIEW: TargetCalculationPreview = {
  targetCgpa: 8.8,
  currentCgpa: 8.34,
  targetSgpa: 9.25,
  requiredSemesterScore: 84.5,
  feasibility: "Challenging",
  formulaExplanation:
    "To lift your cumulative CGPA from 8.34 (over 96 credits) to 8.80 across your degree (120 total credits), you need an average SGPA of ≥ 9.25 in Semesters 5 and 6.",
};
